version: "3.5"
services:
  foo:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    command: node services/foo
    ports:
      - 3000:3000
  bar:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    command: node services/bar
    ports:
      - 3001:3001
  baz:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    command: node services/baz
    ports:
      - 3002:3002
